import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

/*
 * Bundles src/main.ts -> main.js (CommonJS, as Obsidian expects).
 *
 *   node esbuild.config.mjs              watch mode (development)
 *   node esbuild.config.mjs production   one-shot production build
 *   node esbuild.config.mjs test         bundle the pure TeX parser for unit tests
 */
const banner = `/*
This file is generated by esbuild from the TypeScript sources in ./src.
Edit the sources, not this file. Run "npm run build" to regenerate.
*/
`;

const mode = process.argv[2] ?? "dev";

if (mode === "test") {
	await esbuild.build({
		entryPoints: ["src/mirror.ts", "src/math-dom.ts", "src/live-preview.ts", "src/rescue.ts"],
		outdir: "tests/.build",
		bundle: true,
		format: "esm",
		platform: "node",
		target: "node20",
		outExtension: { ".js": ".mjs" },
		// Keep CodeMirror external so the tests share one instance of it.
		external: ["@codemirror/state", "@codemirror/view", "@codemirror/language"],
		logLevel: "warning",
	});
	process.exit(0);
}

const prod = mode === "production";

/** @type {import("esbuild").BuildOptions} */
const options = {
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	outfile: "main.js",
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
};

if (prod) {
	await esbuild.build(options);
	process.exit(0);
}

const context = await esbuild.context(options);
await context.watch();
